apiVersion: v1
kind: Service
metadata:
  name: {{ include "edc-ionos-s3.fullname" . }}
  labels:
    {{- include "edc-ionos-s3.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: {{ .Values.web.http.port }}
      protocol: TCP
      name: api
    - port: {{ .Values.service.managementPort }}
      targetPort: {{ .Values.web.http.management.port }}
      protocol: TCP
      name: management
    - port: {{ .Values.service.idsPort }}
      targetPort: {{ .Values.web.http.ids.port }}
      protocol: TCP
      name: ids
  selector:
    {{- include "edc-ionos-s3.selectorLabels" . | nindent 4 }}
