/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.4.2/userguide/multi_project_builds.html
 */


dependencyResolutionManagement {
    repositories {
        
        mavenCentral()
        mavenLocal()
    }
    versionCatalogs {
        create("libs") {
            from("org.eclipse.edc:edc-versions:0.1.2")
        }
    }
}

include(":extensions:data-plane-ionos-s3")
include(":extensions:provision-ionos-s3")
include(":extensions:core-ionos-s3")

include(":launchers:base:connector")
include(":launchers:dev:connector-consumer")
include(":launchers:dev:connector-provider")
include(":launchers:prod:connector")
include(":launchers:prod:connector-persistence")
