version: "3.9"

services:
  consumer:
    image: edc-ionos-consumer:latest
    ports:
      - "9191:9191"
      - "9192:9192"
      - "9292:9292"
    environment:
      EDC_FS_CONFIG: /resources/consumer-config.properties