version: "3.9"

services:
  hashicorp-vault:
    container_name: hashicorp-vault
    image: vault:1.9.7
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: test-token
      VAULT_ADDR: http://127.0.0.1:8200
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: [ "CMD", "sh", "-c", "sleep 1 && apk add --no-cache curl && curl --fail http://localhost:8200/v1/sys/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5