apiVersion: v1
kind: Service
metadata:
  name: {{ include "dataspace-connector.fullname" . }}
  labels:
    {{- include "dataspace-connector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $k, $v := .Values.ports }}
  - port: {{ default $v.containerPort $v.servicePort }}
    targetPort: {{ $v.containerPort }}
    name: {{ $k }}
    protocol: TCP
  {{- end }}
  selector:
    {{- include "dataspace-connector.selectorLabels" . | nindent 4 }}
