version: "3.9"
services:
  provider:
    build:
      context: ./provider/
    ports:
        - "19191:19191"
        - "19192:19192"            
        - "19193:19193"        
        - "19194:19194"
        - "19195:19195"     
        - "19291:19291" 
    environment:
      EDC_FS_CONFIG: /resources/provider-config.properties
  consumer:
    build:
      context:  ./consumer/
    ports:
        - "29191:29191"
        - "29192:29192"            
        - "29193:29193"        
        - "29194:29194"
        - "29195:29195"     
        - "29291:29291"  
    environment:
      EDC_FS_CONFIG: /resources/consumer-config.properties
  backend-service:
    build:
      context:  ./backend-service/
    ports:
        - "4000:4000"      
  hashicorp-vault:
    container_name: hashicorp-vault
    image: vault:1.9.7
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: test-token
      VAULT_ADDR: http://127.0.0.1:8200
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: [ "CMD", "sh", "-c", "sleep 1 && apk add --no-cache curl && curl --fail http://localhost:8200/v1/sys/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
