# Default values for dataspace-connector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # repository: <container-registry-repository>
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ports: {}
  # Example:
  #  http:
  #    containerPort: 8181
  #    servicePort: 80 (Optional: if not provided, the value of containerPort will be used)
  #    path: /api

volumes: []
  # Define a volume that can then be mounted into a container. Please refer to https://kubernetes.io/docs/concepts/storage/volumes/
  # for more details. Below example will create a volume from the content of the `log-config` ConfigMap keyed with `log_level`:
  # - name: config-vol
  #   configMap:
  #     name: log-config
  #     items:
  #     - key: log_level
  #       path: log_level

edc:
  env: {}
  envSecrets: {}
  volumeMounts: []
  # Mount the provided volume in the POD filesystem at the specific path. Please refer to
  # https://kubernetes.io/fr/docs/concepts/storage/volumes/ for more details.
  # Example:
  # - name: config-vol
  #   mountPath: /etc/config
  # will mount the `config-vol` volume at /etc/config

service:
  type: ClusterIP

ingress:
  enabled: false
  ingressClassName: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: dataspace-connector.local
      paths: []

  tls: []
  #  - secretName: dataspace-connector-tls
  #    hosts:
  #      - dataspace-connector.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
